require 'active_resource'
require 'eventmachine'
require 'em-http-request'
require 'acts_as_hyperactive/acts_as_hyperactive'
require 'acts_as_hyperactive/async_connection'
require 'ext/hash/bytesize'
require 'ext/eventmachine/body'